"""Add dashboards and dashboard tiles

Revision ID: 86aed14377db
Revises: 301581cae64f
Create Date: 2026-08-18 00:04:45.389452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86aed14377db'
down_revision = '301581cae64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_dashboards_user_id'), ['user_id'], unique=False)

    op.create_table('dashboard_tiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('view', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_tiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_tiles_dashboard_id'), ['dashboard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_tiles_message_id'), ['message_id'], unique=False)

    # Autogenerate again proposed altering users.id from NUMERIC to Uuid. That is
    # an artefact of reflecting a SQLite database — sa.UUID and sa.Uuid store
    # identically — so it has been removed rather than run a needless, locking
    # ALTER COLUMN in production. See the note in 301581cae64f.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard_tiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_tiles_message_id'))
        batch_op.drop_index(batch_op.f('ix_dashboard_tiles_dashboard_id'))

    op.drop_table('dashboard_tiles')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_user_id'))
        batch_op.drop_index(batch_op.f('ix_dashboards_share_token'))

    op.drop_table('dashboards')
    # ### end Alembic commands ###
